version: 2.1

orbs:
  ruby: circleci/ruby@1.4.0
  heroku: circleci/heroku@1.2.6

# jobの定義
jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.0
    #githubのコードからコピー
    working_directory: ~/cooklog-api
    steps:
      - checkout:
          path: ~/cooklog-api
      #orbs:bundle installなどを実行するコマンド
      - ruby/install-deps

  test:
    docker:
      - image: cimg/ruby:3.0.0
      - image: cimg/mysql:8.0
        command: |
            mysqld --default-authentication-plugin=mysql_native_password
        environment:
        # databese.ymlに合わして設定する
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: cooklog_test
          MYSQL_ROOT_USER: root
    # testジョブ全体の環境変数
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: 127.0.0.1
      RAILS_ENV: test
    working_directory: ~/cooklog-api
    # stepsで実行するJobを定義
    steps:
      - checkout:
          path: ~/cooklog-api
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rake db:create db:migrate
      - run:
          name: test
          command: bundle exec rspec

  deploy:
    executor: heroku/default
    docker:
      - image: cimg/ruby:3.0.0
    steps:
      - checkout
      #dockerコマンドが使えるように
      - setup_remote_docker:
          version: 20.10.11
      - heroku/install
      - heroku/deploy-via-git

# 実行順
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          context:
            - cooklog-api
            - my_portfolio_context
          filters:
            branches:
              only: master
